"""Phase 0-5 audit fixes: knowledge review + ACL, departments, audit logs,
document sha256/lifecycle fields, chunk token counts + uniqueness, jsonb payloads.

Revision ID: 20261005_0008
Revises: 20261005_0007
Create Date: 2026-10-05
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "20261005_0008"
down_revision = "20261005_0007"
branch_labels = None
depends_on = None

visibility_enum = postgresql.ENUM(
    "all", "department", "admin_only", name="visibility", create_type=False
)
knowledge_status_enum = postgresql.ENUM(
    "pending_review", "approved", "rejected", "archived",
    name="knowledge_status", create_type=False,
)
jsonb = postgresql.JSONB()


def upgrade() -> None:
    # --- shared enum types (shared across documents/chunks/knowledge) ---
    op.execute(
        "DO $$ BEGIN CREATE TYPE visibility AS ENUM ('all','department','admin_only'); "
        "EXCEPTION WHEN duplicate_object THEN NULL; END $$;"
    )
    op.execute(
        "DO $$ BEGIN CREATE TYPE knowledge_status AS ENUM "
        "('pending_review','approved','rejected','archived'); "
        "EXCEPTION WHEN duplicate_object THEN NULL; END $$;"
    )

    # --- departments (Phase 5.5 #2) ---
    op.create_table(
        "departments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_departments_id", "departments", ["id"], unique=False)
    op.create_index("ix_departments_name", "departments", ["name"], unique=True)

    # --- users.department_id ---
    op.add_column("users", sa.Column("department_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        "fk_users_department_id_departments", "users", "departments",
        ["department_id"], ["id"], ondelete="SET NULL",
    )
    op.create_index("ix_users_department_id", "users", ["department_id"], unique=False)

    # --- documents: sha256, uploader, ACL fields ---
    op.add_column("documents", sa.Column("sha256", sa.String(length=64), nullable=True))
    op.create_index("ix_documents_sha256", "documents", ["sha256"], unique=False)
    op.add_column("documents", sa.Column("uploaded_by_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        "fk_documents_uploaded_by_id_users", "documents", "users",
        ["uploaded_by_id"], ["id"], ondelete="SET NULL",
    )
    op.add_column(
        "documents",
        sa.Column("visibility", visibility_enum, nullable=False, server_default=sa.text("'all'")),
    )
    op.add_column(
        "documents",
        sa.Column("department_ids", jsonb, nullable=False, server_default=sa.text("'[]'::jsonb")),
    )

    # --- document_chunks: token_count, ACL, uniqueness ---
    # Existing rows were produced by the old 3-strategy chunker whose indices
    # collide under the new unique(document_id, chunk_index) contract; chunks
    # are derived data and are regenerated by re-running chunking.
    op.execute("DELETE FROM document_chunks")
    op.add_column("document_chunks", sa.Column("token_count", sa.Integer(), nullable=True))
    op.add_column(
        "document_chunks",
        sa.Column("visibility", visibility_enum, nullable=False, server_default=sa.text("'all'")),
    )
    op.add_column(
        "document_chunks",
        sa.Column("department_ids", jsonb, nullable=False, server_default=sa.text("'[]'::jsonb")),
    )
    op.create_unique_constraint(
        "uq_document_chunks_document_chunk_index",
        "document_chunks",
        ["document_id", "chunk_index"],
    )

    # --- knowledge_objects: review workflow + ACL + jsonb ---
    op.add_column(
        "knowledge_objects",
        sa.Column(
            "status", knowledge_status_enum, nullable=False, server_default=sa.text("'pending_review'")
        ),
    )
    op.add_column(
        "knowledge_objects",
        sa.Column("visibility", visibility_enum, nullable=False, server_default=sa.text("'all'")),
    )
    op.add_column(
        "knowledge_objects",
        sa.Column("department_ids", jsonb, nullable=False, server_default=sa.text("'[]'::jsonb")),
    )
    op.add_column("knowledge_objects", sa.Column("confidence", sa.Float(), nullable=True))
    op.add_column("knowledge_objects", sa.Column("created_by_id", sa.Integer(), nullable=True))
    op.add_column("knowledge_objects", sa.Column("reviewed_by_id", sa.Integer(), nullable=True))
    op.add_column("knowledge_objects", sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("knowledge_objects", sa.Column("review_note", sa.Text(), nullable=True))
    op.create_foreign_key(
        "fk_knowledge_objects_created_by_id_users", "knowledge_objects", "users",
        ["created_by_id"], ["id"], ondelete="SET NULL",
    )
    op.create_foreign_key(
        "fk_knowledge_objects_reviewed_by_id_users", "knowledge_objects", "users",
        ["reviewed_by_id"], ["id"], ondelete="SET NULL",
    )
    op.alter_column(
        "knowledge_objects", "payload",
        type_=jsonb, postgresql_using="payload::json",
    )
    op.alter_column(
        "knowledge_objects", "relations",
        type_=jsonb, postgresql_using="relations::json",
    )

    # Data: old version rows become archived history; keep one live row per key.
    op.execute(
        "UPDATE knowledge_objects SET status = 'archived', is_current = false "
        "WHERE is_current = false"
    )
    op.execute(
        "UPDATE knowledge_objects SET status = 'archived', is_current = false "
        "WHERE is_current = true AND status IN ('pending_review','approved') "
        "AND id NOT IN ("
        "  SELECT min(id) FROM knowledge_objects "
        "  WHERE is_current = true AND status IN ('pending_review','approved') "
        "  GROUP BY object_key"
        ")"
    )
    op.execute(
        "CREATE UNIQUE INDEX uq_knowledge_objects_live_key "
        "ON knowledge_objects (object_key) "
        "WHERE status IN ('pending_review','approved')"
    )

    # --- audit_logs (Phase 5.5 #5) ---
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=80), nullable=False),
        sa.Column("entity_type", sa.String(length=80), nullable=True),
        sa.Column("entity_id", sa.String(length=80), nullable=True),
        sa.Column("metadata_json", jsonb, nullable=False),
        sa.Column("ip", sa.String(length=45), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_audit_logs_id", "audit_logs", ["id"], unique=False)
    op.create_index("ix_audit_logs_user_id", "audit_logs", ["user_id"], unique=False)
    op.create_index("ix_audit_logs_action", "audit_logs", ["action"], unique=False)


def downgrade() -> None:
    op.drop_table("audit_logs")
    op.execute("DROP INDEX IF EXISTS uq_knowledge_objects_live_key")
    op.drop_constraint("fk_knowledge_objects_reviewed_by_id_users", "knowledge_objects", type_="foreignkey")
    op.drop_constraint("fk_knowledge_objects_created_by_id_users", "knowledge_objects", type_="foreignkey")
    op.drop_column("knowledge_objects", "review_note")
    op.drop_column("knowledge_objects", "reviewed_at")
    op.drop_column("knowledge_objects", "reviewed_by_id")
    op.drop_column("knowledge_objects", "created_by_id")
    op.drop_column("knowledge_objects", "confidence")
    op.drop_column("knowledge_objects", "department_ids")
    op.drop_column("knowledge_objects", "visibility")
    op.drop_column("knowledge_objects", "status")
    op.alter_column("knowledge_objects", "relations", type_=sa.Text(), existing_nullable=False)
    op.alter_column("knowledge_objects", "payload", type_=sa.Text(), existing_nullable=False)

    op.drop_constraint("uq_document_chunks_document_chunk_index", "document_chunks", type_="unique")
    op.drop_column("document_chunks", "department_ids")
    op.drop_column("document_chunks", "visibility")
    op.drop_column("document_chunks", "token_count")

    op.drop_column("documents", "department_ids")
    op.drop_column("documents", "visibility")
    op.drop_constraint("fk_documents_uploaded_by_id_users", "documents", type_="foreignkey")
    op.drop_column("documents", "uploaded_by_id")
    op.drop_index("ix_documents_sha256", table_name="documents")
    op.drop_column("documents", "sha256")

    op.drop_index("ix_users_department_id", table_name="users")
    op.drop_constraint("fk_users_department_id_departments", "users", type_="foreignkey")
    op.drop_column("users", "department_id")

    op.drop_table("departments")

    op.execute("DROP TYPE IF EXISTS knowledge_status")
    op.execute("DROP TYPE IF EXISTS visibility")
